language: csharp
solution: src/Guitar.sln
install:
  - nuget restore src/Guitar.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release src/Guitar.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./src/bin/Release/Guitar.Tests.dll